[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "toggle_dpms",
  "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]



[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50


[scratchpads.music]
animation = "fromRight"
command = "alacritty --class 'ROCK N ROLL' -e /usr/bin/ncmpcpp"
class = "ROCK N ROLL"
size = "80% 75%"
max_size = "1920px 100%"
margin = 50

# [scratchpads.volume]
# animation = "fromRight"
# command = "pavucontrol"
# class = "pavucontrol"
# size = "40% 90%"
# unfocus = "hide"
# lazy = true
