[window]
decorations = "None"
dynamic_padding = false
opacity = 0.8
blur=true

[window.padding]
x = 2
y = 2


[font]
normal = { family = "Roboto Mono Nerd Font", style = "Regular" }
bold = { family = "Roboto Mono Nerd Font", style = "Bold" }
italic = { family = "Roboto Mono Nerd Font", style = "Italic" }
bold_italic = { family = "Roboto Mono Nerd Font", style = "Bold Italic" }
size = 15.0


# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Heavy"
# 
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Heavy Italic"
# 
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Medium Italic"
# 
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Medium"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "P", mods = "Alt", action = "Paste" },
{ key = "y", mods = "Alt", action = "Copy" },
{ key = "L", mods = "Control|Shift", action = "ResetFontSize" },
# { key = "[", mods = "Control", action = "ToggleViMode" },
]


